name: Update Agenda

on:
  schedule:
    - cron: '0 */3 * * *' # S'exécute toutes les 6 heures
  workflow_dispatch:      # Permet de le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests ics

      - name: Run script
        run: python update_agenda.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add agenda.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour automatique de l'agenda" && git push)
